INSERT INTO `pos_db`.`product` (`name`, `description`, `price`, `instock`, `minstock`, `barcode`, `sku`, `imguri`, `categoryid`) VALUES ('Product 1', 'description 1', '10000', '10', '1', '1234567889', '123456778', 'AAAAA', '1');
INSERT INTO `pos_db`.`category` (`name`, `description`) VALUES ('category1', 'desc 1 csdonv');
INSERT INTO `pos_db`.`client` (`first_name`, `last_name`, `sex`, `rfc`, `birthdate`) VALUES ('Christian', 'Ibarra', 'M', 'LCSFU2345', '1995-07-08');
SELECT `id`, `first_name`, `last_name`, `phone`, `email`, `rfc`, `birthdate`, `store_id`, `user_id` FROM `pos_db`.`employee` WHERE  `id`=1;
UPDATE `pos_db`.`employee` SET `first_name`='john', `last_name`='jpa', `phone`='5555555', `email`='jpa@jpa.com', `rfc`='1234566' WHERE  `id`=1;
INSERT INTO `pos_db`.`expense` (`concept`, `date`, `employee_id`, `currency`, `store_id`, `amount`) VALUES ('Electricity', '2022-07-10', '1', 'MXN', '1', '1000');
INSERT INTO `pos_db`.`provider` (`name`, `address`) VALUES ('Metal Providers', 'Washington 22');
INSERT INTO `pos_db`.`role` (`description`, `name`) VALUES ('Has all privileges', 'admin');
INSERT INTO `pos_db`.`sale` (`detail_id`, `employee_id`, `discount`, `amount`, `currency`, `client_id`, `tax`, `observations`, `store_id`, `date`) VALUES ('1', '1', '100.0', '25', 'EUR', '1', '16.5', 'none', '1', '2022-07-10');
INSERT INTO `pos_db`.`store` (`name`, `manager_id`, `address`) VALUES ('Store 1', '1', 'Washington 900');